# Generated by Django 5.2.5 on 2025-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transaçao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaçao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.RenameField(
            model_name='transaçao',
            old_name='categoria',
            new_name='catego',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='dt_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaçao',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaçao',
            name='observaçao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
