# Generated by Django 5.2.5 on 2025-08-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transaçao_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaçao',
            old_name='catego',
            new_name='categoria',
        ),
    ]
